const SEED_INGREDIENTS = [
  { id: "i_jaje", name: "Jaje, cijelo, sirovo", state: "as_sold", kcal: 143, p: 12.6, c: 0.7, f: 9.5 },
  { id: "i_zob", name: "Zobene pahuljice, suhe", state: "raw", kcal: 379, p: 13.2, c: 67.7, f: 6.5 },
  { id: "i_skyr", name: "Skyr 0% m.m.", state: "as_sold", kcal: 63, p: 11.0, c: 4.0, f: 0.2 },
  { id: "i_puretina_nar", name: "Pureća prsa, narezak", state: "as_sold", kcal: 104, p: 18.6, c: 1.2, f: 1.0 },
  { id: "i_maslac", name: "Maslac", state: "as_sold", kcal: 717, p: 0.9, c: 0.1, f: 81.1 },
  { id: "i_kecap", name: "Kečap", state: "as_sold", kcal: 101, p: 1.0, c: 27.1, f: 0.1 },
  { id: "i_rajcica", name: "Rajčica, svježa", state: "raw", kcal: 18, p: 0.9, c: 3.9, f: 0.2 },
  { id: "i_piletina", name: "Pileća prsa, sirova", state: "raw", kcal: 120, p: 22.5, c: 0, f: 2.6 },
  { id: "i_riza", name: "Riža, bijela, kuhana", state: "cooked", kcal: 130, p: 2.7, c: 28.2, f: 0.3 },
  { id: "i_krumpir", name: "Krumpir, sirovi", state: "raw", kcal: 77, p: 2.0, c: 17.5, f: 0.1 },
  { id: "i_whey", name: "Whey protein (prah)", state: "as_sold", kcal: 400, p: 80, c: 8, f: 5 },
  { id: "i_banana", name: "Banana", state: "raw", kcal: 89, p: 1.1, c: 22.8, f: 0.3 },
];

const SEED_RECIPES = [
  {
    id: "r_omlet", name: "Proteinski omlet sa zobi i skyrom", slot: "dorucak",
    servings: 1, mode: "items",
    items: [
      { ing: "i_jaje", g: 200 }, { ing: "i_zob", g: 50 }, { ing: "i_skyr", g: 100 },
      { ing: "i_maslac", g: 5 }, { ing: "i_puretina_nar", g: 50 },
      { ing: "i_kecap", g: 15 }, { ing: "i_rajcica", g: 100 },
    ],
    macros: null,
    steps: [
      "Izmuti jaja pa umiješaj zob, skyr, sol i papar dok ne nestanu grudice.",
      "Ostavi smjesu 2 minute da zob upije tekućinu — omlet se lakše okreće.",
      "Otopi maslac na srednjoj vatri; ne pojačavaj, maslac tamni brže od ulja.",
      "Peci 2-3 minute dok se rubovi ne stegnu i sredina prestane biti tekuća.",
      "Okreni pomoću tanjura i peci još 1-2 minute.",
      "Serviraj s kečapom, narezanom puretinom i rajčicom.",
    ],
  },
  {
    id: "r_oats_breskva", name: "Peach cheesecake overnight oats", slot: "dorucak",
    servings: 1, mode: "direct", items: [], macros: { kcal: 410, p: 42, c: 38, f: 8 },
    ing: [
      "Baza: 40 g zobenih pahuljica, 10 g mljevenih lanenih sjemenki, 120 ml bademovog mlijeka, 30 g skyra, 15 g wheya (vanilija), malo limunove korice",
      "Krema: 150 g skyra, 15 g wheya (vanilija), Natren po ukusu",
      "Vrh: 1 porcija ohlađenog preljeva od breskve",
    ],
    steps: [
      "U teglici pomiješaj zob, mljeveni lan, whey, žlicu skyra, limunovu koricu i bademovo mlijeko. Utisni na dno.",
      "Izmiješaj skyr, ostatak wheya i Natren pa premaži preko baze.",
      "Na vrh stavi ohlađeni preljev od breskve.",
      "Zatvori teglicu i ostavi u hladnjaku preko noći.",
    ],
  },
  {
    id: "r_oats_tiramisu", name: "Tiramisu overnight oats", slot: "dorucak",
    servings: 1, mode: "direct", items: [], macros: { kcal: 400, p: 42, c: 36, f: 7 },
    ing: [
      "Baza: 40 g zobenih pahuljica, 10 g mljevenih lanenih sjemenki, 60 ml hladne crne kave, 70 ml bademovog mlijeka, 15 g wheya, Natren",
      "Krema: 150 g skyra, 15 g wheya, par kapi arome ruma",
      "Posip: 1 žličica organskog kakaa",
    ],
    steps: [
      "Pomiješaj zob, lan, whey, hladnu kavu, mlijeko i Natren pa utisni na dno teglice.",
      "Izmiješaj skyr, ostatak wheya i aromu ruma u glatku kremu pa premaži preko baze.",
      "Ostavi u hladnjaku preko noći.",
      "Ujutro, tik prije jela, kroz cjedilo obilno pospi kakaom.",
    ],
  },
  {
    id: "r_banana_bread", name: "Banana bread u šalici", slot: "dorucak",
    servings: 1, mode: "direct", items: [], macros: { kcal: 333, p: 42, c: 30, f: 3 },
    ing: [
      "50 g crne banane",
      "45 g wheya (vanilija, banana ili čokolada)",
      "20 g sitnih zobenih pahuljica",
      "50 g skyra 0%",
      "1/4 žličice praška za pecivo",
      "Natren po ukusu",
      "prstohvat cimeta",
    ],
    steps: [
      "U šalici koja smije u mikrovalnu vilicom zgnječi bananu u kašu bez grudica.",
      "Umiješaj skyr i par kapi Natrena.",
      "Dodaj zob, whey, prašak za pecivo i cimet pa energično miješaj u gustu smjesu.",
      "Ako je pregusta, dodaj žlicu vode, mlijeka ili hladne kave.",
      "Peci na najjačoj snazi 1 minutu i 30 sekundi, po potrebi još 15-30 sekundi.",
      "Ostavi da odstoji minutu-dvije prije jela.",
    ],
  },
  {
    id: "r_burek_sir", name: "Fitness burek sa sirom", slot: "vecera",
    servings: 1, mode: "direct", items: [], macros: { kcal: 241, p: 22.8, c: 17.5, f: 8.1 },
    ing: [
      "2 lista rižinog papira (cca 16 g)",
      "100 g posnog sira 0.5% m.m.",
      "15 g fete ili salatnog sira",
      "1 jaje (M, cca 50 g)",
      "10 ml mlijeka 1.5% m.m.",
      "sol, papar",
    ],
    steps: [
      "Umuti jaje, mlijeko i prstohvat soli u širokom i dubokom tanjuru.",
      "Pomiješaj posni sir, dobro razmrvljenu fetu i papar. Dodaj i ostatak smjese od jajeta koji preostane nakon natapanja.",
      "Uroni prvi list rižinog papira na 5-8 sekundi, položi na papir za pečenje, pa preko njega drugi natopljeni list.",
      "Rasporedi nadjev u ravnoj liniji uz donji rub, čvrsto zaroljaj u valjak pa smotaj u zvrk.",
      "Air fryer: 200 °C, 10 minuta. Pećnica: 200 °C, 15-20 minuta.",
    ],
  },
  {
    id: "r_burek_meso", name: "Fitness burek s puretinom", slot: "vecera",
    servings: 1, mode: "direct", items: [], macros: { kcal: 288, p: 26.5, c: 16.8, f: 11.2 },
    ing: [
      "2 lista rižinog papira (cca 16 g)",
      "100 g mljevenog purećeg zabatka (5-7% masti)",
      "30 g crvenog luka",
      "2 žlice vode",
      "1 bjelanjak (za natapanje papira)",
      "1/2 žličice soli, dosta papra, češnjak u prahu",
      "1 žličica maslinovog ulja za premaz",
    ],
    steps: [
      "Izgnječi mljevenu puretinu sa sitno sjeckanim lukom, soli, dosta papra, češnjakom i 2 žlice vode dok se ne poveže.",
      "Razmuti bjelanjak s 2 žlice vode i prstohvatom soli u plitkom tanjuru.",
      "Uroni dva lista rižinog papira po 5-8 sekundi i posloži jedan preko drugog.",
      "Rasporedi meso uz rub, čvrsto zaroljaj i smotaj u zvrk. Zbog sirovog mesa zvrk je mekši, pa rukuj pažljivo.",
      "Premaži kistom s žličicom maslinovog ulja — bez toga papir ne postaje hrskav.",
      "Air fryer: 180 °C, 12-15 minuta. Pećnica: 190 °C, 20 minuta.",
    ],
  },
  {
    id: "r_seafood", name: "Creamy seafood bake", slot: "vecera",
    servings: 2, mode: "direct", items: [], macros: { kcal: 580, p: 76, c: 20, f: 18 },
    ing: [
      "250 g očišćenih škampa",
      "150 g kapica ili bijele ribe",
      "150 g šampinjona",
      "2 šake špinata",
      "1 luk, 2 češnja češnjaka",
      "150 g skyra, 50 g light krem sira",
      "50 ml bademovog mlijeka",
      "30 g light mozzarelle",
      "češnjak u prahu, limun, sol, papar",
    ],
    steps: [
      "Na par kapi ulja kratko ispeci škampe i kapice, 1-2 minute po strani, pa ih izvadi.",
      "U istoj tavi prodinstaj luk i šampinjone; pred kraj dodaj češnjak i špinat da uvene.",
      "Umuti skyr, light krem sir, bademovo mlijeko i začine.",
      "Smanji vatru na minimum, ulij umak u povrće, vrati plodove mora i lagano promiješaj.",
      "Prebaci u posudu za pečenje, pospi mozzarellom i zapeci na 200 °C pod gornjim grijačem 5-7 minuta.",
    ],
  },
  {
    id: "r_umak_jogurt", name: "Umak od jogurta", slot: "vecera",
    servings: 1, mode: "direct", items: [], macros: { kcal: 43, p: 4.2, c: 5, f: 0.5 },
    ing: [
      "100 g jogurta 0.5% m.m. ili skyra",
      "1/4 žličice češnjaka u prahu",
      "sol, sušeni kopar ili peršin",
      "par kapi limunovog soka",
    ],
    steps: [
      "Pomiješaj jogurt, češnjak, sol, sušeni kopar ili peršin i par kapi limunovog soka.",
      "Ostavi u hladnjaku 5-10 minuta da se okusi prožmu.",
    ],
  },
  {
    id: "r_cheesecake_peceni", name: "Pečeni low-cal cheesecake", slot: "uzina",
    servings: 4, mode: "direct", items: [], macros: { kcal: 780, p: 115, c: 60, f: 14 },
    ing: [
      "Podloga: 60 g zobenih pahuljica samljevenih u brašno, 1 žlica meda, 3 žlice mlijeka",
      "Krema: 400 g skyra, 200 g zrnatog sira (light), 2 jaja, 30 g wheya (vanilija), 1 ravna žlica gustina, Natren",
    ],
    steps: [
      "Pomiješaj zobeno brašno, med i mlijeko pa utisni na dno kalupa od 18-20 cm obloženog papirom.",
      "Izblendaj zrnati sir štapnim mikserom dok ne bude potpuno gladak.",
      "Dodaj skyr, jaja, whey, gustin i Natren pa izmiksaj u glatku kremu.",
      "Izlij preko podloge i peci na 160 °C 45-50 minuta; sredina smije lagano drhtati.",
      "Ugasi pećnicu i ostavi kolač unutra s poluotvorenim vratima 15 minuta.",
      "Hladi u hladnjaku minimalno 4 sata prije rezanja.",
    ],
  },
  {
    id: "r_cheesecake_nobake", name: "No-bake cheesecake", slot: "uzina",
    servings: 4, mode: "direct", items: [], macros: { kcal: 650, p: 100, c: 55, f: 5 },
    ing: [
      "Podloga: 60 g sitnih zobenih pahuljica, 1 žlica meda, 3 žlice mlijeka",
      "Krema: 400 g skyra, 200 g zrnatog sira (light), 30 g wheya (vanilija), 10 g mljevene želatine, Natren",
    ],
    steps: [
      "Pomiješaj zob, med i mlijeko pa utisni na dno kalupa.",
      "Želatinu prelij s 4 žlice hladne vode i ostavi 10 minuta da nabubri, zatim je lagano zagrij da se otopi — ne smije proključati.",
      "Izblendaj zrnati sir, skyr, whey i Natren u glatku smjesu.",
      "U toplu želatinu umiješaj jednu žlicu kreme da izjednačiš temperaturu, pa sve ulij natrag i brzo izmiksaj.",
      "Izlij preko podloge i ostavi u hladnjaku 2-3 sata da se stisne.",
    ],
  },
  {
    id: "r_mousse", name: "Čokoladni protein mousse", slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 320, p: 43, c: 12, f: 5 },
    ing: [
      "300 g skyra",
      "15-20 g organskog kakaa",
      "2 bjelanjka",
      "Natren po ukusu",
      "par kapi arome vanilije",
    ],
    steps: [
      "Izmiksaj bjelanjke u čistoj posudi u čvrsti snijeg.",
      "U drugoj posudi pomiješaj skyr, kakao, Natren i vaniliju u glatku tamnu kremu.",
      "Špatulom, ne mikserom, nježno umiješaj snijeg žlicu po žlicu, pokretima odozdo prema gore.",
      "Podijeli u čaše i ohladi barem 1 sat.",
    ],
  },
  {
    id: "r_monte", name: 'Fitnes "Monte" u čaši', slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 290, p: 46, c: 8, f: 3 },
    ing: [
      "250 g skyra (150 g + 100 g)",
      "30 g wheya (vanilija ili bijela čokolada)",
      "1 žličica organskog kakaa",
      "1-2 žlice bademovog mlijeka",
      "Natren po ukusu",
    ],
    steps: [
      "Pomiješaj 150 g skyra i cijelu mjericu wheya od vanilije u gustu kremu pa prebaci na dno čaše.",
      "U preostalih 100 g skyra umiješaj kakao, Natren i bademovo mlijeko u sjajnu kremu.",
      "Izlij čokoladnu kremu preko vanilije i ohladi u zamrzivaču 15 minuta.",
    ],
  },
  {
    id: "r_mugcake", name: "Protein čokoladni mug cake", slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 230, p: 22, c: 22, f: 4 },
    ing: [
      "30 g zobenih pahuljica samljevenih u brašno",
      "15 g wheya",
      "5 g organskog kakaa",
      "1/2 žličice praška za pecivo",
      "30 g skyra",
      "4-5 žlica bademovog ili običnog mlijeka",
      "Natren",
    ],
    steps: [
      "U šalici vilicom pomiješaj zobeno brašno, whey, kakao i prašak za pecivo.",
      "Dodaj skyr, Natren i mlijeko pa izmiješaj u gustu, glatku smjesu.",
      "Peci u mikrovalnoj na najjačoj snazi 60-80 sekundi; sredina treba ostati sočna.",
    ],
  },
  {
    id: "r_snickers", name: 'Protein "Snickers" u čaši', slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 340, p: 38, c: 26, f: 6 },
    ing: [
      "Nugat: 150 g skyra, 15 g wheya, 10 g kikiriki maslaca u prahu (PB2), Natren",
      "Karamel: 2 mekane datulje, 1 žlica tople vode, mrvica soli, 5 g sjeckanih kikirikija",
      "Čokolada: 5 g organskog kakaa, 15 g čokoladnog wheya, 2-3 žlice bademovog mlijeka",
    ],
    steps: [
      "U čaši vilicom izmiješaj skyr, whey, kikiriki maslac u prahu i Natren pa poravnaj žlicom.",
      "Zgnječi datulje s malo tople vode i mrvicom soli, premaži preko nugata i pospi sjeckanim kikirikijem.",
      "Pomiješaj kakao, čokoladni whey i bademovo mlijeko u gusti umak pa prelij na vrh.",
      "Ostavi u zamrzivaču 15-20 minuta da se čokolada stisne.",
    ],
  },
  {
    id: "r_strudla", name: "Štrudla od jabuka (rižin papir)", slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 174, p: 1.2, c: 32.5, f: 4.8 },
    ing: [
      "2 lista rižinog papira (cca 16 g)",
      "1 srednja jabuka (cca 150 g)",
      "1 žlica eritrita ili par kapi stevije",
      "1 žličica cimeta, par kapi limunovog soka",
      "30 ml bademovog mlijeka + aroma vanilije (za natapanje)",
      "1 žličica kokosovog ulja za premaz",
    ],
    steps: [
      "Naribaj jabuku i dinstaj je s cimetom, sladilom i limunovim sokom 3-5 minuta dok većina tekućine ne ispari. Ohladi.",
      "U široki tanjur ulij bademovo mlijeko s par kapi arome vanilije.",
      "Uroni dva lista rižinog papira po 5-8 sekundi i posloži jedan preko drugog.",
      "Rasporedi jabuke uz donji rub i čvrsto zaroljaj u valjak.",
      "Premaži cijelu površinu otopljenim kokosovim uljem — to daje hrskavost.",
      "Air fryer: 190 °C, 10-12 minuta. Pećnica: 200 °C, 15 minuta.",
    ],
  },
  {
    id: "r_preljev_breskva", name: "Preljev od breskve", slot: "uzina",
    servings: 1, mode: "direct", items: [], macros: { kcal: 60, p: 1, c: 15, f: 0 },
    ing: [
      "1 zrela breskva (cca 150 g)",
      "1 žlica vode",
      "Natren po ukusu",
      "limunov sok ili cimet (opcionalno)",
    ],
    steps: [
      "Stavi kockice breskve, Natren i žlicu vode u manji lončić.",
      "Kuhaj 5-8 minuta na srednje laganoj vatri i usput gnječi vilicom.",
      "Kad tekućina ispari i breskva postane ljepljiva, makni s vatre i ohladi.",
    ],
  },
];
